/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class EvenFibonnachiNUmbers {

	public static void main(String[] args) {
		int sum=0;// used to find the sum of even numbered fibonnachi numbers
		int[] fibArray=new int[9999]; // create an array to store the first 4000000 fibonacchi numbers
		fibArray[0]=1; fibArray[1]=2;
		for(int i=2;fibArray[i-1]+fibArray[i-2]<4000000;i++)
		{
			fibArray[i]=fibArray[i-1]+fibArray[i-2];
			if(fibArray[i]%2==0)
				sum=sum+fibArray[i];
		}
		sum=sum+2;
		System.out.println(""+sum);
		// TODO Auto-generated method stub

	}

}
